#!/bin/bash

# Setup script for EZProxy Web Extension project
# This script helps configure the Xcode project with the new targets

echo "EZProxy Web Extension Project Setup"
echo "===================================="
echo ""
echo "This script will guide you through setting up the Xcode project."
echo ""

# Check if Xcode is installed
if ! command -v xcodebuild &> /dev/null; then
    echo "Error: Xcode is not installed. Please install Xcode first."
    exit 1
fi

echo "Instructions for setting up the project in Xcode:"
echo ""
echo "1. Open EZProxy.xcodeproj in Xcode"
echo ""
echo "2. Remove old targets:"
echo "   - Select 'EZProxy Safari' target"
echo "   - Press Delete key and confirm removal"
echo "   - Select 'EZProxy' target" 
echo "   - Press Delete key and confirm removal"
echo ""
echo "3. Add new Universal App target:"
echo "   - File → New → Target"
echo "   - Choose 'App' under Multiplatform"
echo "   - Product Name: 'EZProxy Universal'"
echo "   - Interface: SwiftUI"
echo "   - Language: Swift"
echo "   - Bundle Identifier: com.cornelius-bell.EZProxy"
echo "   - Include Tests: Optional"
echo ""
echo "4. Add Web Extension target:"
echo "   - File → New → Target"
echo "   - Choose 'Safari Extension' under macOS (or iOS)"
echo "   - Select 'Safari Web Extension'"
echo "   - Product Name: 'EZProxy Web Extension'"
echo "   - Language: Swift"
echo "   - Bundle Identifier: com.cornelius-bell.EZProxy.WebExtension"
echo ""
echo "5. Configure Universal App:"
echo "   - Select 'EZProxy Universal' target"
echo "   - General tab:"
echo "     * Deployment Info → macOS: 12.0"
echo "     * Deployment Info → iOS: 15.0"
echo "   - Signing & Capabilities:"
echo "     * Add 'App Groups' capability"
echo "     * Add group: HK6R36PLNR.com.cornelius-bell"
echo "   - Build Phases → Compile Sources:"
echo "     * Add: EZProxyApp.swift"
echo "     * Add: SettingsView.swift"
echo "     * Add: SettingsViewModel.swift"
echo ""
echo "6. Configure Web Extension:"
echo "   - Select 'EZProxy Web Extension' target"
echo "   - General tab:"
echo "     * Deployment Info → macOS: 11.0"
echo "     * Deployment Info → iOS: 15.0"
echo "   - Signing & Capabilities:"
echo "     * Add 'App Groups' capability"
echo "     * Add group: HK6R36PLNR.com.cornelius-bell"
echo "   - Build Phases → Compile Sources:"
echo "     * Add: SafariWebExtensionHandler.swift"
echo "   - Build Phases → Copy Bundle Resources:"
echo "     * Add entire Resources folder"
echo ""
echo "7. Set up embedding:"
echo "   - Select 'EZProxy Universal' target"
echo "   - General tab → Frameworks, Libraries, and Embedded Content"
echo "   - Add 'EZProxy Web Extension.appex'"
echo ""
echo "8. Clean up old references:"
echo "   - Remove red (missing) file references from the project navigator"
echo "   - Remove Pods group if it still exists"
echo ""
echo "9. Build Settings (for both targets):"
echo "   - Set 'Swift Language Version' to 5.0"
echo "   - Set 'Build Active Architecture Only' Debug to Yes"
echo ""
echo "10. Test the build:"
echo "    - Select 'EZProxy Universal' scheme"
echo "    - Build (⌘B) for macOS"
echo "    - Switch to iOS simulator and build again"
echo ""

echo "Would you like to open Xcode now? (y/n)"
read -r response

if [[ "$response" == "y" || "$response" == "Y" ]]; then
    open EZProxy.xcodeproj
    echo ""
    echo "Xcode opened. Please follow the instructions above."
else
    echo ""
    echo "You can open the project later with: open EZProxy.xcodeproj"
fi

echo ""
echo "After setting up the project, you may need to:"
echo "- Add app icons to the Assets catalog"
echo "- Configure code signing with your developer account"
echo "- Add extension icons to Resources/images/"
echo ""
echo "For more details, see MIGRATION_GUIDE.md"